### ISSUE TITLE
Implement a CSS parser

### ISSUE THREAD

**Issue by georgelemon** [openpeeps/bro#1]
`@import plain.css` should parse the CSS file and turn it into a BRO-compatible abstract syntax tree. This is a **must-have feature** that would make it easier to work with all CSS frameworks 👌

Some CSS:
```css
.btn {
  font-size: 16px;
  color: blue
}
```
Some `.bass` file: 
```bass
@import main.css

.btn-secondary
  @extend .btn
  if this.has("color"):
    echo this.color // will print `blue`
```
