### ISSUE TITLE
Compiler optimizations

### ISSUE THREAD

**Issue by georgelemon** [openpeeps/bro#7]
- Autoprefixer

- Deduplication
```bass
.btn 
  color: blue

.btn
  font-size: 14px
```

should output a single `.btn` selector
```css
.btn{color: blue; font-size: 14px}
```

Other cool features:
- CSS alphabetize (done by `std/critbits`)
